ERROR:root:Time: 2016-12-09 21:47:42.274000 File: scrapeCodeforcesProblem.py Line: 28 Caused By: insecure string pickle
ERROR:root:2016-12-09 21:48:06.862000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 21:48:08.214000 :File Name: sqlDB.pyc :Line Number: 73 :Caused By: (2003, "Can't connect to MySQL server on 'localhost' (10061)")
ERROR:root:2016-12-09 21:48:10.341000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 21:48:11.342000 :File Name: sqlDB.pyc :Line Number: 73 :Caused By: (2003, "Can't connect to MySQL server on 'localhost' (10061)")
ERROR:root:2016-12-09 21:48:13.295000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 21:48:14.299000 :File Name: sqlDB.pyc :Line Number: 73 :Caused By: (2003, "Can't connect to MySQL server on 'localhost' (10061)")
ERROR:root:Time: 2016-12-09 21:48:16.220000 File: CodeforcesProblemPage.pyc Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/741/D Caused By: [Errno 10054] An existing connection was forcibly closed by the remote host
