ERROR:root:Time: 2016-12-09 00:38:12.631000 File: CodeforcesProblem.pyc Line: 40 ProblemUrl: http://codeforces.com/problemset/problem/730/B Caused By: Input not found
ERROR:root:Time: 2016-12-09 00:38:25.835000 File: CodeforcesProblem.pyc Line: 40 ProblemUrl: http://codeforces.com/problemset/problem/727/C Caused By: Input not found

ERROR:root:Time: 2016-12-09 08:47:58.207000 File: scrapeCodeforcesProblem.py Line: 27 Caused By: insecure string pickle
ERROR:root:2016-12-09 08:48:19.933000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:Time: 2016-12-09 08:48:21.894000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/741/B Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:23.568000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/741/A Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:24.332000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/740/B Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:25.175000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/740/A Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:26.058000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/739/E Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:27.205000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/739/D Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:2016-12-09 08:48:28.170000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:Time: 2016-12-09 08:48:29.048000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/739/B Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:30.001000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/739/A Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:31.564000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/737/F Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:32.451000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/737/E Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:33.357000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/736/E Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:34.154000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/736/D Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:34.986000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/735/E Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:36.036000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/735/D Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:36.852000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/735/C Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:48:37.232000 File: CodeforcesProblemPage.py Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/735/B Caused By: [Errno 10054] An existing connection was forcibly closed by the remote host
ERROR:root:Time: 2016-12-09 08:50:17.478000 File: CodeforcesProblemPage.pyc Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/742/A Caused By: Message: chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)

ERROR:root:Time: 2016-12-09 08:50:21.634000 File: CodeforcesProblemPage.pyc Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/741/E Caused By: Message: chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)

ERROR:root:Time: 2016-12-09 08:50:25.810000 File: CodeforcesProblemPage.pyc Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/741/D Caused By: Message: chrome not reachable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)

ERROR:root:Time: 2016-12-09 08:50:29.297000 File: CodeforcesProblemPage.pyc Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/741/C Caused By: [Errno 10054] An existing connection was forcibly closed by the remote host
ERROR:root:2016-12-09 08:50:51.828000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:50:53.266000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:50:54.776000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:50:56.922000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:50:58.528000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:00.131000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:01.022000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:01.640000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:02.418000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:03.043000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:03.703000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:04.694000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:05.382000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:06.666000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:07.419000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:08.096000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:08.696000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:09.538000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:10.392000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:11.317000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:12.471000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:13.166000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:14.161000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:15.194000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:16.404000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:17.358000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:18.365000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:19.164000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:20.260000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:21.233000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:22.024000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:22.792000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:23.763000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:24.802000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:25.738000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:26.893000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:2016-12-09 08:51:27.903000 :File Name: sqlDB.pyc :Line Number: 68 :Caused By: coercing to Unicode: need string or buffer, list found
ERROR:root:Time: 2016-12-09 08:51:28.299000 File: CodeforcesProblemPage.pyc Line: 22 ProblemUrl: http://codeforces.com/problemset/problem/732/C Caused By: [Errno 10054] An existing connection was forcibly closed by the remote host
ERROR:root:Time: 2016-12-09 08:56:49.730000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/732/C Caused By: 'charmap' codec can't encode characters in position 57-59: character maps to <undefined>
ERROR:root:2016-12-09 08:56:49.731000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:50.977000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/732/B Caused By: 'charmap' codec can't encode characters in position 53-55: character maps to <undefined>
ERROR:root:2016-12-09 08:56:50.977000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:51.869000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/732/A Caused By: 'charmap' codec can't encode characters in position 63-65: character maps to <undefined>
ERROR:root:2016-12-09 08:56:51.869000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:52.842000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/731/F Caused By: 'charmap' codec can't encode characters in position 64-66: character maps to <undefined>
ERROR:root:2016-12-09 08:56:52.842000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:53.672000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/731/E Caused By: 'charmap' codec can't encode characters in position 60-62: character maps to <undefined>
ERROR:root:2016-12-09 08:56:53.673000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:54.522000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/731/D Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:56:54.522000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:55.432000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/731/C Caused By: 'charmap' codec can't encode characters in position 67-69: character maps to <undefined>
ERROR:root:2016-12-09 08:56:55.432000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:56.157000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/731/B Caused By: 'charmap' codec can't encode characters in position 60-62: character maps to <undefined>
ERROR:root:2016-12-09 08:56:56.157000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 08:56:57.378000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:58.285000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/L Caused By: 'charmap' codec can't encode characters in position 64-66: character maps to <undefined>
ERROR:root:2016-12-09 08:56:58.285000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:56:59.459000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/K Caused By: 'charmap' codec can't encode characters in position 231-233: character maps to <undefined>
ERROR:root:2016-12-09 08:56:59.459000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:00.299000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/J Caused By: 'charmap' codec can't encode characters in position 51-53: character maps to <undefined>
ERROR:root:2016-12-09 08:57:00.299000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:01.262000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/I Caused By: 'charmap' codec can't encode characters in position 74-76: character maps to <undefined>
ERROR:root:2016-12-09 08:57:01.263000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:02.140000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/H Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:02.140000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:03.183000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/G Caused By: 'charmap' codec can't encode characters in position 42-44: character maps to <undefined>
ERROR:root:2016-12-09 08:57:03.183000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:04.126000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/F Caused By: 'charmap' codec can't encode characters in position 60-62: character maps to <undefined>
ERROR:root:2016-12-09 08:57:04.127000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:05.032000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/E Caused By: 'charmap' codec can't encode characters in position 69-71: character maps to <undefined>
ERROR:root:2016-12-09 08:57:05.033000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:06.031000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/D Caused By: 'charmap' codec can't encode characters in position 53-55: character maps to <undefined>
ERROR:root:2016-12-09 08:57:06.032000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:06.951000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/C Caused By: 'charmap' codec can't encode characters in position 50-52: character maps to <undefined>
ERROR:root:2016-12-09 08:57:06.951000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:07.882000 File: CodeforcesProblem.py Line: 45 ProblemUrl: http://codeforces.com/problemset/problem/730/B Caused By: Input not found
ERROR:root:Time: 2016-12-09 08:57:07.882000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/730/B Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:Time: 2016-12-09 08:57:08.630000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/730/A Caused By: 'charmap' codec can't encode characters in position 51-53: character maps to <undefined>
ERROR:root:2016-12-09 08:57:08.631000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:09.810000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/729/F Caused By: 'charmap' codec can't encode characters in position 58-60: character maps to <undefined>
ERROR:root:2016-12-09 08:57:09.810000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:10.575000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/729/E Caused By: 'charmap' codec can't encode characters in position 62-64: character maps to <undefined>
ERROR:root:2016-12-09 08:57:10.576000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:11.380000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/729/D Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:11.380000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:12.145000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/729/C Caused By: 'charmap' codec can't encode characters in position 69-71: character maps to <undefined>
ERROR:root:2016-12-09 08:57:12.145000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:13.045000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/729/B Caused By: 'charmap' codec can't encode characters in position 62-64: character maps to <undefined>
ERROR:root:2016-12-09 08:57:13.046000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:13.745000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/729/A Caused By: 'charmap' codec can't encode characters in position 53-55: character maps to <undefined>
ERROR:root:2016-12-09 08:57:13.746000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:14.804000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/727/F Caused By: 'charmap' codec can't encode characters in position 62-64: character maps to <undefined>
ERROR:root:2016-12-09 08:57:14.805000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 08:57:14.808000 :File Name: sqlDB.pyc :Line Number: 80 :Caused By: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's problems', 'http://codeforces.com/problemset/problem/727/F', 'F. Polycarps pro' at line 1")
ERROR:root:Time: 2016-12-09 08:57:15.545000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/727/E Caused By: 'charmap' codec can't encode characters in position 75-77: character maps to <undefined>
ERROR:root:2016-12-09 08:57:15.545000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:16.488000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/727/D Caused By: 'charmap' codec can't encode character u'\u2009' in position 228: character maps to <undefined>
ERROR:root:2016-12-09 08:57:16.489000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:17.282000 File: CodeforcesProblem.py Line: 45 ProblemUrl: http://codeforces.com/problemset/problem/727/C Caused By: Input not found
ERROR:root:Time: 2016-12-09 08:57:17.282000 File: scrapeCodeforcesProblem.py Line: 63 ProblemsListPageUrl: http://codeforces.com/problemset/ ProblemUrl: http://codeforces.com/problemset/problem/727/C Caused By: CodeforcesProblem instance has no attribute 'statement'
ERROR:root:2016-12-09 08:57:18.043000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:18.799000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/727/A Caused By: 'charmap' codec can't encode characters in position 62-64: character maps to <undefined>
ERROR:root:2016-12-09 08:57:18.800000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:19.839000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/725/G Caused By: 'charmap' codec can't encode characters in position 62-64: character maps to <undefined>
ERROR:root:2016-12-09 08:57:19.839000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:20.770000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/725/F Caused By: 'charmap' codec can't encode characters in position 60-62: character maps to <undefined>
ERROR:root:2016-12-09 08:57:20.771000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:21.576000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/725/E Caused By: 'charmap' codec can't encode characters in position 34-36: character maps to <undefined>
ERROR:root:2016-12-09 08:57:21.577000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:22.460000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/725/D Caused By: 'charmap' codec can't encode characters in position 68-70: character maps to <undefined>
ERROR:root:2016-12-09 08:57:22.460000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 08:57:23.322000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:24.188000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/725/B Caused By: 'charmap' codec can't encode characters in position 95-97: character maps to <undefined>
ERROR:root:2016-12-09 08:57:24.189000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:25.055000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/725/A Caused By: 'charmap' codec can't encode characters in position 64-66: character maps to <undefined>
ERROR:root:2016-12-09 08:57:25.055000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:25.838000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/724/G Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:25.839000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:26.555000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/724/F Caused By: 'charmap' codec can't encode characters in position 74-76: character maps to <undefined>
ERROR:root:2016-12-09 08:57:26.556000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:27.361000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/724/E Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:27.362000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:28.142000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/724/D Caused By: 'charmap' codec can't encode characters in position 64-66: character maps to <undefined>
ERROR:root:2016-12-09 08:57:28.143000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:29.188000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/724/C Caused By: 'charmap' codec can't encode characters in position 71-73: character maps to <undefined>
ERROR:root:2016-12-09 08:57:29.189000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:30.124000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/724/B Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:30.124000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:2016-12-09 08:57:30.976000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:31.897000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/723/F Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:31.897000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:32.750000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/723/E Caused By: 'charmap' codec can't encode characters in position 53-55: character maps to <undefined>
ERROR:root:2016-12-09 08:57:32.751000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:33.581000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/723/D Caused By: 'charmap' codec can't encode characters in position 71-73: character maps to <undefined>
ERROR:root:2016-12-09 08:57:33.582000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
ERROR:root:Time: 2016-12-09 08:57:34.313000 File: CodeforcesProblem.py Line: 82 ProblemUrl: http://codeforces.com/problemset/problem/723/C Caused By: 'charmap' codec can't encode characters in position 66-68: character maps to <undefined>
ERROR:root:2016-12-09 08:57:34.314000 :File Name: sqlDB.pyc :Line Number: 11 :Caused By: [Errno 2] No such file or directory: 'dbINFO.txt'
