ERROR:root:Time: 2016-12-09 00:38:12.631000 File: CodeforcesProblem.pyc Line: 40 ProblemUrl: http://codeforces.com/problemset/problem/730/B Caused By: Input not found
ERROR:root:Time: 2016-12-09 00:38:25.835000 File: CodeforcesProblem.pyc Line: 40 ProblemUrl: http://codeforces.com/problemset/problem/727/C Caused By: Input not found

